"use client";

import { useEffect, useRef } from "react";
import Image from "next/image";
import Link from "next/link";
import type { Photo } from "@/content/photos";
import { site } from "@/lib/site";
import { applyFrame, actOf, type Stagehands } from "./drive";
import "@/styles/hero.css";

/**
 * "Jo Ruk Gaya" — six acts, driven entirely by scroll position.
 *
 * WHY THERE IS NO WEBGL HERE
 * The brief was a crowd nobody can tell is fake. The reliable way to get that
 * is not to simulate people — simulated people always read as cheap — but to
 * move Hammad's own photographs past the viewport under real directional blur.
 * The crowd is not a model of humanity, it *is* the humanity he shot. It also
 * keeps three.js out of the bundle and degrades to a still photograph instead
 * of a black canvas when anything goes wrong.
 *
 * WHAT ACTUALLY MOVES
 * Only transform, opacity and filter — all compositor properties. The rAF loop
 * hands the frame to `applyFrame` in drive.ts, which writes straight to the
 * eleven elements that move. That file explains why this is not done with CSS
 * custom properties: writing one on the stage invalidates the computed style
 * of its whole subtree, and this subtree is fifty photographs.
 *
 * `data-act` is the one thing still written on the stage, and only when it
 * changes — the HUD reads its caption off it in CSS.
 */

/** Which baked blur each lane uses, back to front. Generated by
 *  scripts/make-motion.mjs. */
const LANE_BLUR = ["soft", "mid", "near"] as const;

type HeroProps = {
  /** Photographs that flow past. */
  crowd: Photo[];
  /** The one who stops. */
  stopped: Photo;
  /** The frame that gets taken in act four. */
  captured: Photo;
};

export default function Hero({ crowd, stopped, captured }: HeroProps) {
  const wrap = useRef<HTMLElement>(null);
  const stage = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const wrapEl = wrap.current;
    const stageEl = stage.current;
    if (!wrapEl || !stageEl) return;

    /* Reduced motion gets the end of the story, immediately and still: the
       photograph, taken, developed, with the line under it. */
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
      stageEl.dataset.static = "true";
      wrapEl.dataset.static = "true";
      return;
    }

    const coarse = window.matchMedia("(pointer: coarse)").matches;

    /* Collected once. Every frame then writes to these elements and nothing
       else — see drive.ts for why that matters so much here. */
    const q = <T extends HTMLElement>(sel: string) => stageEl.querySelector<T>(sel);
    const hands: Stagehands = {
      river: q(".hero__river"),
      part: q(".hero__part"),
      still: q(".hero__still"),
      stillTag: q(".hero__still-tag"),
      grey: q(".hero__grey"),
      finder: q(".hero__finder"),
      lock: q(".hero__lock"),
      bladeTop: q('[data-blade="top"]'),
      bladeBottom: q('[data-blade="bottom"]'),
      flash: q(".hero__flash"),
      print: q(".hero__print"),
      printCap: q(".hero__print-cap"),
      copy: q(".hero__copy"),
      scrim: q(".hero__scrim"),
      hudBar: q(".hero__hud-bar i"),
      hud: q(".hero__hud"),
      cue: q(".hero__cue"),
      pans: Array.from(stageEl.querySelectorAll<HTMLElement>(".hero__pan")),
    };

    let tx = 0.5;
    let ty = 0.5;
    let mx = 0.5;
    let my = 0.5;
    let p = 0;
    let raf = 0;

    const readScroll = () => {
      const rect = wrapEl.getBoundingClientRect();
      const travel = wrapEl.offsetHeight - window.innerHeight;
      const raw = travel > 0 ? -rect.top / travel : 0;
      p = raw < 0 ? 0 : raw > 1 ? 1 : raw;
    };

    const point = (cx: number, cy: number) => {
      tx = cx / window.innerWidth;
      ty = cy / window.innerHeight;
    };
    const onPointer = (e: PointerEvent) => point(e.clientX, e.clientY);
    const onTouch = (e: TouchEvent) => {
      const t = e.touches[0];
      if (t) point(t.clientX, t.clientY);
    };

    const frame = () => {
      // The viewfinder lags the pointer. A camera does not snap to where you
      // look — it trails, and that lag is most of why this feels like glass.
      mx += (tx - mx) * 0.085;
      my += (ty - my) * 0.085;

      applyFrame(hands, p, mx, my);

      const act = String(actOf(p));
      if (stageEl.dataset.act !== act) stageEl.dataset.act = act;

      raf = requestAnimationFrame(frame);
    };

    readScroll();
    raf = requestAnimationFrame(frame);

    window.addEventListener("scroll", readScroll, { passive: true });
    window.addEventListener("resize", readScroll);
    if (coarse) window.addEventListener("touchmove", onTouch, { passive: true });
    else window.addEventListener("pointermove", onPointer, { passive: true });

    return () => {
      window.removeEventListener("scroll", readScroll);
      window.removeEventListener("resize", readScroll);
      window.removeEventListener("touchmove", onTouch);
      window.removeEventListener("pointermove", onPointer);
      cancelAnimationFrame(raf);
    };
  }, []);

  /* Three lanes, back to front. Photographs are dealt round-robin so no lane
     is all cats or all campus, then each lane repeats until it is comfortably
     wider than any viewport — a track narrower than the screen shows the seam
     where the loop restarts. The stride is coprime with the lane length so a
     repeat never puts the same face next to itself. */
  const LANES = 3;
  const PER_LANE = 8;
  const lanes = Array.from({ length: LANES }, (_, lane) => {
    const mine = crowd.filter((_, i) => i % LANES === lane);
    if (!mine.length) return mine;
    const gcd = (a: number, b: number): number => (b ? gcd(b, a % b) : a);
    const stride = [3, 5, 2, 1].find((s) => s < mine.length && gcd(s, mine.length) === 1) ?? 1;
    return Array.from(
      { length: Math.max(PER_LANE, mine.length) },
      (_, i) => mine[(i * stride) % mine.length],
    );
  }).filter((l) => l.length > 0);

  return (
    <section className="hero" ref={wrap} aria-label="Introduction">
      <div className="hero__stage" ref={stage} data-act="1">
        <div className="hero__world">
          {/* ---- ACTS 1-3 : the river of people ---- */}
          <div className="hero__river" aria-hidden="true">
            {lanes.map((lane, i) => (
              <div className="hero__lane" key={i} data-lane={i}>
                {/* .hero__pan carries the pointer parallax so it never fights
                    the infinite loop animation running on .hero__track. */}
                <div className="hero__pan">
                  <div className="hero__track">
                    {/* Doubled so the loop has no seam. */}
                    {[...lane, ...lane].map((photo, j) => (
                      <div className="hero__body" key={`${photo.slug}-${j}`}>
                        {/* A plain <img>, deliberately. These are pre-blurred
                            420px files generated by scripts/make-motion.mjs —
                            already the exact size they render at, so next/image
                            would add a round trip and a srcset for nothing.
                            eslint-disable-next-line @next/next/no-img-element */}
                        <img
                          src={`/gallery/motion/${photo.slug}-${LANE_BLUR[i]}.jpg`}
                          alt=""
                          width={420}
                          height={560}
                          loading={i === 2 && j < 3 ? "eager" : "lazy"}
                          decoding="async"
                          draggable={false}
                        />
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* ---- ACT 2 : the crowd parts, then the one who stopped ---- */}
          <div className="hero__part" aria-hidden="true" />

          <div className="hero__still guard" aria-hidden="true">
            <Image
              src={`/gallery/${stopped.slug}.jpg`}
              alt=""
              width={1200}
              height={1500}
              sizes="(max-width: 700px) 72vw, 34vw"
              quality={84}
              priority
              draggable={false}
            />
            <span className="hero__still-tag mono">still</span>
          </div>

          {/* ---- ACT 3 : the grey. Everything under this loses its colour
                 except the hole the viewfinder cuts. One image decode, not two. */}
          <div className="hero__grey" aria-hidden="true" />

          {/* ---- ACT 3 : the viewfinder ---- */}
          <div className="hero__finder" aria-hidden="true">
            <span className="hero__bracket" data-c="tl" />
            <span className="hero__bracket" data-c="tr" />
            <span className="hero__bracket" data-c="bl" />
            <span className="hero__bracket" data-c="br" />
            <span className="hero__grid" />
            <span className="hero__crosshair" />
            <span className="hero__readout mono">f/1.8 · 1/125 · iso 400</span>
            <span className="hero__lock mono">focus locked</span>
          </div>

          {/* ---- ACT 4 : the shutter, then the print developing ---- */}
          <div className="hero__blade" data-blade="top" aria-hidden="true" />
          <div className="hero__blade" data-blade="bottom" aria-hidden="true" />
          <div className="hero__flash" aria-hidden="true" />

          <figure className="hero__print guard">
            <Image
              src={`/gallery/${captured.slug}.jpg`}
              alt={captured.alt}
              width={1400}
              height={1866}
              sizes="(max-width: 700px) 84vw, 46vw"
              quality={88}
              draggable={false}
            />
            <span className="hero__print-grain" aria-hidden="true" />
            <figcaption className="hero__print-cap">
              <span className="urdu">{captured.urdu.split("\n")[0]}</span>
              <span className="mono">{captured.title}</span>
            </figcaption>
          </figure>
        </div>

        {/* Film grain over the whole stage. It is the single cheapest thing
            that stops a dark web page looking like a dark web page. */}
        <div className="hero__film" aria-hidden="true" />
        <div className="hero__vignette" aria-hidden="true" />
        <div className="hero__scrim" aria-hidden="true" />

        {/* ---- the opening: black, one line of Nastaliq, then the street ---- */}
        <div className="hero__curtain" aria-hidden="true">
          <p className="urdu urdu--center hero__ink">{site.urduTagline}</p>
        </div>

        {/* ---- words ---- */}
        <div className="hero__copy shell">
          <p className="hero__kicker mono">
            {site.role} · {site.location.city}
          </p>

          <h1 className="hero__title display">
            <span className="hero__line" data-l="1">
              Sab guzar rahe the.
            </span>
            <span className="hero__line" data-l="2">
              <em>Main ruk gaya.</em>
            </span>
          </h1>

          <p className="hero__urdu urdu">{site.urduTagline}</p>

          <p className="hero__sub">
            Everyone was passing. I stopped. I&nbsp;photograph the people Karachi walks past — and I
            write down why.
          </p>

          <div className="hero__acts">
            <Link className="hero__go" href="/work" data-cursor="link">
              See the work
            </Link>
            <Link className="hero__go" data-ghost href="/hire" data-cursor="link">
              Book a shoot
            </Link>
          </div>
        </div>

        {/* ---- the camera's own HUD. Content comes from CSS, keyed on
                data-act, so narrating the acts costs no JavaScript. ---- */}
        <div className="hero__hud mono" aria-hidden="true">
          <span className="hero__hud-act" />
          <span className="hero__hud-bar">
            <i />
          </span>
        </div>

        <div className="hero__cue mono" aria-hidden="true">
          <span>scroll</span>
          <span className="hero__cue-line" />
        </div>
      </div>
    </section>
  );
}
